name: Build StarWarsRashad (Forge 1.12.2)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Java 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'

    - name: Grant execute to gradlew
      run: chmod +x ./gradlew

    - name: Build (skip tests)
      run: ./gradlew build -x test --no-daemon
      env:
        _JAVA_OPTIONS: "-Xmx4G"

    - name: Upload jar artifact
      uses: actions/upload-artifact@v4
      with:
        name: StarWarsRashad-jar
        path: build/libs/*.jar

